image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9
stages:
 - build
 - test
build-stage:
 stage: build
 script:
   - dotnet restore
   - dotnet build
   - dotnet publish
 artifacts:
   paths:
     - Proflo-portal-backend/bin/Debug/dotnetcoreapp2.2/publish
 tags:
   - immersive-cgi-w7-dotnet
test-stage:
 stage: test
 script:
   - dotnet test Core_BackendTest/Core_BackendTest.csproj
 tags:
   - immersive-cgi-w7-dotnet
